spring.application.name=java-example

cms.init.config-file-path=${CMS_PROPERTIES_FILE}
cms.init.unix-socket-path=${CMS_UNIX_SOCKET_PATH}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true