spring.application.name=server

server.address=0.0.0.0
server.port=${HTTP_PORT:8080}

spring.threads.virtual.enabled=true
spring.lifecycle.timeout-per-shutdown-phase=30s

server.shutdown=graceful

# gRPC Server Configuration
spring.grpc.server.port=${GRPC_PORT:9090}
spring.grpc.server.address=0.0.0.0

app.server.raft.node-id=${RAFT_NODE_ID}
app.server.raft.host=${RAFT_NODE_HOST}
app.server.raft.port=${RAFT_NODE_PORT:6000}
app.server.raft.storage-dir=.data/raft/${app.server.raft.node-id}
app.server.raft.group-id=${RAFT_GROUP}
app.server.raft.heartbeat-interval-ms=${RAFT_HEARTBEAT_INTERVAL_MS:1000}
app.server.raft.election-timeout-ms=${RAFT_ELECTION_TIMEOUT_MS:5000}
app.server.raft.request-timeout-ms=${RAFT_REQUEST_TIMEOUT_MS:7000}
app.server.raft.peers=${RAFT_PEERS}
app.server.raft.peer-http-port=8080

app.property.current-version=1
app.property.max-value-size-bytes=${MAX_VALUE_BYTES:1048576}

app.server.web.no-cors-urls=${CORS_URLS}