syntax = "proto3";

package com.fyordo.cms;

service AgentChannelService {
  rpc WatchProperties (stream AgentStreamEvent) returns (stream ServerStreamEvent);
}

message AgentStreamEvent {
  oneof command {
    AgentConnectEvent connectEvent = 1;
    AgentAckEvent ackEvent = 2;
  }
}

message AgentConnectEvent {
  string namespace = 1;
  string service = 2;
  string appId = 3;
}

message AgentAckEvent {
  int64 revision = 1;
}

message ServerStreamEvent {
  oneof command {
    ServerInitEvent initEvent = 1;
    ServerPropertyUpdateEvent updateEvent = 2;
  }
}

message Property {
  string key = 1;
  bytes value = 2;
  int64 modifiedMs = 3;
}

message ServerInitEvent {
  repeated Property properties = 1;
  int64 revision = 2;
}

message ServerPropertyUpdateEvent {
  Property property = 1;
  int64 revision = 2;
}